### PR TITLE
catch errors when invalid QR-code has been scanned

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [AGCORDOVA-93](https://issues.jboss.org/browse/AGCORDOVA-93)

### CODE REVIEW

**Comment by edewit** [comment]
@abstractj can you verify this one?

to test remove the plugin and then add the one from this branch with
```bash
cordova plugin add https://github.com/edewit/aerogear-otp-cordova.git\#generation
```

**Comment by danielpassos** [comment]
:eyes:

**Comment by danielpassos** [comment]
:+1:  

Tested using https://github.com/aerogear/aerogear-cordova-cookbook/pull/19

**Comment by abstractj** [comment]
@edewit @danielpassos landed https://github.com/aerogear/aerogear-cordova-otp/commit/ac620846fbc7150e286e761299a53817991018c9

**Pull request closed without merging**
